# Tokyo Night color scheme for kitty terminal emulator
# https://github.com/davidmathers/tokyo-night-kitty-theme
#
# Based on Tokyo Night color theme for Visual Studio Code
# https://github.com/enkia/tokyo-night-vscode-theme


#-----------------------------------#
# Custom key maps
#####################################
map ctrl+w close_tab
map ctrl+shift+] move_tab_forward
map ctrl+shift+[ move_tab_backward


#-----------------------------------#
# Colours
#####################################
foreground #a9b1d6
background #1a1b26

# Black
color0 #414868
color8 #414868

# Red
color1 #f7768e
color9 #f7768e

# Green
color2  #73daca
color10 #73daca

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #c0caf5
color15 #c0caf5

# The color for highlighting URLs on mouse-over
url_color #9ece6a
#-----------------------------------#


#-----------------------------------#
# System
#####################################
shell_integration no-cursor
linux_display_server auto
enable_audio_bell no
#-----------------------------------#


#-----------------------------------#
# Cursor
#####################################
cursor #c0caf5
cursor_text_color #1a1b26
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0
#-----------------------------------#


#-----------------------------------#
# Scrollbar
#####################################
scrollbar always
scrollbar_width 0.8
scrollbar_radius 0.5
scrollbar_gap 0.3
scrollbar_track_opacity 0.05
#-----------------------------------#


#-----------------------------------#
# Selection highlight
#####################################
selection_foreground none
selection_background #28344a


#-----------------------------------#
# Window
#####################################
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #e0af68

window_padding_width 8

background_opacity 0.90
#-----------------------------------#


#-----------------------------------#
# Tab bar
#####################################
tab_bar_style powerline
tab_powerline_style slanted
tab_title_min_length 8
tab_title_max_length 20

tab_bar_edge bottom
tab_bar_align left
tab_bar_min_tabs 1

tab_activity_symbol " "
tab_title_template "{fmt.fg.color1}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}"

active_tab_foreground   #1a1b26
active_tab_background   #a9b1d6
active_tab_font_style   normal
inactive_tab_foreground #c0caf5
inactive_tab_background #414868
inactive_tab_font_style normal
tab_bar_background #24283b


#-----------------------------------#
# Tokyo Night Storm mod
#####################################
# background #24283b
# cursor_text_color #24283b
# active_tab_background   #1f2335
# inactive_tab_background #1f2335
# macos_titlebar_color #1f2335
#-----------------------------------#


#-----------------------------------#
# Font
#####################################
font_size 14.0
font_family      family="FiraMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
#-----------------------------------#
